mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=wordpress
web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=123456
    ports:
     - "127.0.0.1:8222:80"
    working_dir: /var/www/html
    volumes:
     - wordpress:/var/www/html
